version: '3'

services:
  tomcat:
    build:
      context: ./tomcat
      dockerfile: Dockerfile
    # user: "${UID_GID}"
    volumes:
      - ./:/app
      - ./webapps:/usr/local/tomcat/webapps
    ports:
      - 8888:8080
    environment:
      - "MAVEN_OPTS=-Dmaven.repo.local=/app/.m2"
    networks:
      - br0

  mysql:
    container_name: mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    platform: linux/x86_64
    tty: true
    user: "${UID_GID}"
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "study"
      MYSQL_USER: "system"
      MYSQL_PASSWORD: "system"
      MYSQL_ROOT_PASSWORD: "system"
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - br0
  # java:
  #   container_name: java
  #   image: maven:3.8.6-openjdk-18
  #   user: "${UID_GID}"
  #   tty: true
  #   command: "/bin/bash"
  #   volumes:
  #     - ./:/app
  #   working_dir: /app/src
  #   environment:
  #     - "MAVEN_OPTS=-Dmaven.repo.local=/app/.m2"

networks:
  br0:
    driver: bridge
