version: '3'

services:
  tomcat:
    image: tomcat:9.0.13-jre11-slim
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
    ports:
      - 8080:8080

  mysql:
    container_name: mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    platform: linux/x86_64
    tty: true
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=study
      - MYSQL_USER=system
      - MYSQL_ROOT_PASSWORD=system
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
